Trigger a new build of 0.16.3 as subclassing currently fails
Objects in the current version of MongoEngine 0.16.3 on Conda-Forge cannot be subclassed in Python 3 due to a Python 2 dictionary `iteritems` method in `metaclass.py`

The following snippet is the minimal case to recreate the error from a fresh Conda install (with conda-forge channel as higher priority)
```bash
conda install --yes mongoengine
python```
Then within Python
```python
from mongoengine import Document as D
class Foo(D):
    pass
```
throws the following:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "{conda_root}/envs/me/lib/python3.7/site-packages/mongoengine/base/metaclasses.py", line 330, in __new__
    meta.merge(base._meta)
  File "{conda_root}/envs/me/lib/python3.7/site-packages/mongoengine/base/metaclasses.py", line 441, in merge
    for k, v in new_options.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

However, doing a local build from cloning this repo, making no changes, and installing the local build allows the above script to work.
I think something went wrong during the dependency resolution when building this which would not have shown up in tests at the time (likely the `six` package).

Because a local build works fine, I think simply bumping the build version and allowing a new build to be pushed will resolve this issue (and will not remove old builds from the existing cloud)